import type { SupportedLocale } from './types';

const glossary: Record<SupportedLocale, Record<string, string>> = {
  ja: {
    'font-family': '選択範囲内で文字を表示している要素の優先フォントです。',
    'font-size': '文字の大きさです。',
    'font-weight': '文字の太さです。400が標準、700が太字の目安です。',
    'line-height': '行と行の間隔を含む、1行分の高さです。',
    'letter-spacing': '文字同士の間隔です。',
    'text-align': '行の中で文字をどこに揃えるかを指定します。',
    color: '文字に使われる色です。',
    'background-color': '要素の背景に使われる色です。',
    'border-color': '境界線に使われる色です。',
    margin: '要素の外側に確保される余白です。',
    padding: '要素の内側、内容との間に確保される余白です。',
    gap: '行や列として並ぶ子要素同士の間隔です。',
    border: '要素の境界線の太さ、種類、色です。',
    'border-radius': '角の丸みです。値が大きいほど丸くなります。',
    'box-shadow': '要素の周囲に描画される影です。',
    opacity: '要素全体の透明度です。1が不透明、0が透明です。',
    display: '要素と子要素をどのレイアウト方式で配置するかを決めます。',
    position: '要素を通常の流れ、固定、追従などのどの方法で配置するかを決めます。',
    'flex-direction': 'Flexboxで子要素を並べる方向です。',
    'justify-content': '主軸方向で子要素をどう分配するかを指定します。',
    'align-items': '交差軸方向で子要素をどう揃えるかを指定します。',
    'grid-template-columns': 'Gridレイアウトの列幅と列数です。',
    overflow: '内容が要素の領域からはみ出したときの扱いです。',
    'z-index': '重なり順です。大きい値ほど手前に表示されます。',
  },
  en: {
    'font-family': 'Preferred fonts on text-bearing elements inside the selection.',
    'font-size': 'The rendered size of the text.',
    'font-weight': 'The thickness of the text; 400 is regular and 700 is typically bold.',
    'line-height': 'The height of each line, including space between lines.',
    'letter-spacing': 'The amount of space between characters.',
    'text-align': 'Where text is aligned within each line.',
    color: 'The color used to render text.',
    'background-color': 'The color painted behind the element.',
    'border-color': 'The color used for the element border.',
    margin: 'Space outside the element.',
    padding: 'Space inside the element between its edge and content.',
    gap: 'Space between children arranged in rows or columns.',
    border: 'The width, style, and color of the element boundary.',
    'border-radius': 'How rounded the corners are.',
    'box-shadow': 'The shadow painted around the element.',
    opacity: 'Transparency of the entire element; 1 is opaque and 0 is transparent.',
    display: 'The layout model used for the element and its children.',
    position: 'How the element is placed in normal flow or relative to the viewport.',
    'flex-direction': 'The direction children flow in Flexbox.',
    'justify-content': 'How children are distributed along the main axis.',
    'align-items': 'How children align along the cross axis.',
    'grid-template-columns': 'The number and size of columns in a grid.',
    overflow: 'What happens when content extends beyond the element.',
    'z-index': 'The stacking order; larger values usually appear in front.',
  },
  zh: {
    'font-family': '所选范围内用于显示文字的元素所指定的首选字体。',
    'font-size': '文字的显示大小。',
    'font-weight': '文字的粗细；400通常为常规，700通常为粗体。',
    'line-height': '每行的高度，包括行与行之间的间距。',
    'letter-spacing': '字符之间的间距。',
    'text-align': '文字在每一行中的对齐方式。',
    color: '用于显示文字的颜色。',
    'background-color': '绘制在元素背后的颜色。',
    'border-color': '元素边框使用的颜色。',
    margin: '元素外侧的间距。',
    padding: '元素边缘与内容之间的内侧间距。',
    gap: '按行或列排列的子元素之间的间距。',
    border: '元素边界的宽度、样式和颜色。',
    'border-radius': '元素圆角的大小。',
    'box-shadow': '绘制在元素周围的阴影。',
    opacity: '整个元素的透明度；1为不透明，0为完全透明。',
    display: '元素及其子元素所使用的布局模式。',
    position: '元素在正常文档流中或相对视口的定位方式。',
    'flex-direction': 'Flexbox中子元素的排列方向。',
    'justify-content': '子元素沿主轴的分布方式。',
    'align-items': '子元素沿交叉轴的对齐方式。',
    'grid-template-columns': '网格布局中的列数和列宽。',
    overflow: '内容超出元素区域时的处理方式。',
    'z-index': '元素的层叠顺序；数值越大通常越靠前。',
  },
};

export function explainProperty(name: string, value = '', locale: SupportedLocale = 'ja'): string {
  const specialized: Record<SupportedLocale, Record<string, string>> = {
    ja: {
      'display:flex': '子要素をFlexboxで配置しています。',
      'display:grid': '子要素を行と列のGridで配置しています。',
      'position:sticky': 'スクロール中、指定位置に達するとその位置に留まる要素です。',
      'position:fixed': 'viewportを基準に固定され、スクロールしても同じ位置に表示されます。',
    },
    en: {
      'display:flex': 'Children are arranged with Flexbox.',
      'display:grid': 'Children are arranged in grid rows and columns.',
      'position:sticky': 'The element stays at a specified position while scrolling.',
      'position:fixed': 'The element stays fixed to the viewport while scrolling.',
    },
    zh: {
      'display:flex': '子元素使用Flexbox排列。',
      'display:grid': '子元素按网格的行和列排列。',
      'position:sticky': '滚动到指定位置后，元素会停留在该位置。',
      'position:fixed': '元素相对视口固定，滚动时仍显示在同一位置。',
    },
  };
  const explanation = specialized[locale][`${name}:${value}`];
  if (explanation) return explanation;
  return (
    glossary[locale][name] ??
    {
      ja: 'ブラウザが最終的に適用したCSSの値です。',
      en: 'The final computed CSS value used by the browser.',
      zh: '浏览器最终应用的CSS计算值。',
    }[locale]
  );
}
